// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KP2r4fX5XlG_91V1c8WOdcgR60cXY7c',
    appId: '1:307631848175:web:909d0894ebdd72c279391a',
    messagingSenderId: '307631848175',
    projectId: 'suzumakukar-780ff',
    authDomain: 'suzumakukar-780ff.firebaseapp.com',
    storageBucket: 'suzumakukar-780ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwFFhld2KYtxUUgQdlzvxxshk4s-TDVxo',
    appId: '1:307631848175:android:63cb103f730308a979391a',
    messagingSenderId: '307631848175',
    projectId: 'suzumakukar-780ff',
    storageBucket: 'suzumakukar-780ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX5ipGgQy1vgNH7EQIWrbt4EX0JDuIuzA',
    appId: '1:307631848175:ios:2def3cde3e39ae7879391a',
    messagingSenderId: '307631848175',
    projectId: 'suzumakukar-780ff',
    storageBucket: 'suzumakukar-780ff.appspot.com',
    iosBundleId: 'com.example.suzumakukar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX5ipGgQy1vgNH7EQIWrbt4EX0JDuIuzA',
    appId: '1:307631848175:ios:332a48e48dd610b279391a',
    messagingSenderId: '307631848175',
    projectId: 'suzumakukar-780ff',
    storageBucket: 'suzumakukar-780ff.appspot.com',
    iosBundleId: 'com.example.suzumakukar.RunnerTests',
  );
}
